[package]
name = "ggemini"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "Glib-oriented client for Gemini protocol"
keywords = ["gemini", "gemini-protocol", "gtk", "gio", "client"]
categories = ["development-tools", "network-programming"]
repository = "https://github.com/YGGverse/ggemini"

[dependencies.gtk]
package = "gtk4"
version = "0.9.1"
